spring:
  application:
    name: mall-member
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.183.131:3306/mall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.183.131:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
